# general
seed: 3008
logging: 'local_test'
device: 'cpu'

# model
model: 'stofnet'
model_file: 'tough-shadow-532_rf-scale20_epoch_10.pth'

# training
batch_size: 4
lr: 0.001
epochs: 80
weight_decay: 1e-8
upsample_factor: 4
evaluate: False
patience: 5
delta: 1e-3

# loss
lambda_value: 1
mask_amplitude: 50
kernel_size: 7
sigma: 1
th: Null
nms_win_size: 7 

# dataset
sequences: [1]
rf_scale_factor: 20
ch_gap: 16
clutter_db: Null
temporal_filter: False
pow_law_opt: False
angle_threshold: 75
etol: 1
crop_ratio: 0.8
snr_db: 35

# paths
data_path: PALA_data_InSilicoFlow/
ubx_dir: /storage/workspaces/artorg_aimi/ws_00000/chris/${data_path}
loc_dir: ./datasets/stof_chirp101_dataset #/home/chris/LocalDatasets/03_PALA/${data_path} # 
map_dir: /home/chris/UbelixWorkspaces/artorg_aimi/ws_00000/chris/${data_path}
ubx_rat_dir: /storage/workspaces/artorg_aimi/ws_00000/chris/Rat18_2D_InVivoBrain/
map_rat_dir: /home/chris/UbelixWorkspaces/artorg_aimi/ws_00000/chris/Rat18_2D_InVivoBrain/
data_dir: ${loc_dir}