# general
seed: 3008
logging: 'local_test'
device: 'cuda'

# model
model: 'stofnet'
model_file: Null

# training
batch_size: 4
lr: 5e-4
epochs: 80
weight_decay: 1e-8
upsample_factor: 4
evaluate: False
patience: 5
delta: 1e-6

# loss
lambda_value: 1e-2
mask_amplitude: 20
kernel_size: 7
sigma: 1
th: 0.5
nms_win_size: 7 

# dataset
sequences: [0,1,2,3,4]
rf_scale_factor: 10
ch_gap: 32
clutter_db: Null
temporal_filter: False
pow_law_opt: False
angle_threshold: 60
etol: 1
crop_ratio: 0.75
snr_db: 30

# paths
data_path: PALA_data_InSilicoFlow/ #Rat18_2D_InVivoBrain/
ubx_dir: /storage/workspaces/artorg_aimi/ws_00000/chris/${data_path}
loc_dir: /home/chris/LocalDatasets/03_PALA/${data_path}
map_dir: /home/chris/UbelixWorkspaces/artorg_aimi/ws_00000/chris/${data_path}
data_dir: ${ubx_dir}
